# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'iosApp.xcworkspace'

target 'iosApp' do
  pod 'SQLCipher', '< 4.0'
  pod 'shared', :path => '../shared'

end

target 'SQLCipherTest' do
  project '../SQLCipherTest/SQLCipherTest.xcodeproj'
  pod 'SQLCipher', '< 4.0'
end

